drop table user if exists;
create table user (id bigint generated by default as identity (start with 1), email varchar(255) not null, password_hash varchar(255) not null, role varchar(255) not null, primary key (id));
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)